# Generated by Django 5.2.13 on 2026-05-15 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0009_exporthistory_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('lead_insight', 'Lead Insight'), ('full_personalization', 'Full Personalization')], default='full_personalization', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('lead_ids', models.JSONField(blank=True, default=list)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('completed_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('skipped_items', models.PositiveIntegerField(default=0)),
                ('credit_cost', models.PositiveIntegerField(default=0)),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AILeadInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_priority', models.CharField(choices=[('very_high', 'Very High'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('skip', 'Skip')], db_index=True, default='medium', max_length=30)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('ai_suggested_offer', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_offer_reason', models.TextField(blank=True, null=True)),
                ('ai_best_channel', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_channel_reason', models.TextField(blank=True, null=True)),
                ('ai_first_line', models.TextField(blank=True, null=True)),
                ('ai_email_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_email_body', models.TextField(blank=True, null=True)),
                ('ai_followup_1', models.TextField(blank=True, null=True)),
                ('ai_followup_2', models.TextField(blank=True, null=True)),
                ('ai_facebook_message', models.TextField(blank=True, null=True)),
                ('ai_whatsapp_message', models.TextField(blank=True, null=True)),
                ('ai_website_weakness', models.TextField(blank=True, null=True)),
                ('ai_local_seo_opportunity', models.TextField(blank=True, null=True)),
                ('ai_score_explanation', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(default='gemini', max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insight', to='leads.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_lead_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(default='gemini', max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('request_type', models.CharField(default='lead_insight', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='ai.aijob')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='leads.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aijob',
            index=models.Index(fields=['user', 'status'], name='ai_aijob_user_id_dc1f10_idx'),
        ),
        migrations.AddIndex(
            model_name='aijob',
            index=models.Index(fields=['job_type', 'status'], name='ai_aijob_job_typ_9e609c_idx'),
        ),
        migrations.AddIndex(
            model_name='aijob',
            index=models.Index(fields=['created_at'], name='ai_aijob_created_9747b2_idx'),
        ),
        migrations.AddIndex(
            model_name='aileadinsight',
            index=models.Index(fields=['user', 'ai_priority'], name='ai_aileadin_user_id_9dcb18_idx'),
        ),
        migrations.AddIndex(
            model_name='aileadinsight',
            index=models.Index(fields=['generated_at'], name='ai_aileadin_generat_3a3fef_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['user', 'created_at'], name='ai_aiusagel_user_id_e34bca_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['request_type'], name='ai_aiusagel_request_5ca707_idx'),
        ),
    ]
