# Generated by Django 5.2.13 on 2026-05-15 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('leads', '0009_exporthistory_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aijob',
            name='campaign_goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aijob',
            name='custom_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aijob',
            name='outreach_channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aijob',
            name='target_audience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aijob',
            name='target_offer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aijob',
            name='tone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aileadinsight',
            name='campaign_goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aileadinsight',
            name='custom_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aileadinsight',
            name='outreach_channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aileadinsight',
            name='target_audience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aileadinsight',
            name='target_offer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aileadinsight',
            name='tone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='aileadinsight',
            index=models.Index(fields=['target_offer'], name='ai_aileadin_target__002048_idx'),
        ),
        migrations.AddIndex(
            model_name='aileadinsight',
            index=models.Index(fields=['outreach_channel'], name='ai_aileadin_outreac_347002_idx'),
        ),
    ]
