# Generated by Django 5.2.13 on 2026-05-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aijob_campaign_goal_aijob_custom_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aileadinsight',
            name='ai_followup_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aileadinsight',
            name='ai_linkedin_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aijob',
            name='tone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='aileadinsight',
            name='tone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
