# Generated by Django 5.2.13 on 2026-05-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='map_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
