# Generated by Django 5.2.13 on 2026-05-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_map_link_alter_lead_website'),
        ('searches', '0002_search_email_enrichment_search_max_leads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='keyword',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='location',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('invalid', 'Invalid')], db_index=True, default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['search', 'created_at'], name='leads_lead_search__287985_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['keyword', 'location'], name='leads_lead_keyword_03dbba_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['rating'], name='leads_lead_rating_d07f03_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['review_count'], name='leads_lead_review__389a1d_idx'),
        ),
    ]
