# Generated by Django 5.2.13 on 2026-05-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_created_at_alter_lead_keyword_and_more'),
        ('searches', '0004_search_updated_at_alter_search_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_keyword_03dbba_idx',
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('search', 'name', 'phone', 'website')},
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['search', 'keyword', 'location'], name='leads_lead_search__19d9ef_idx'),
        ),
    ]
