# Generated by Django 5.2.13 on 2026-05-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_leadlist_leadlistitem_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='website_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('no_website', 'No Website'), ('working', 'Working'), ('broken', 'Broken'), ('404', '404'), ('expired_domain', 'Expired Domain'), ('redirect_error', 'Redirect Error'), ('social_only', 'Social Only'), ('free_builder', 'Free Builder'), ('under_construction', 'Under Construction'), ('timeout', 'Timeout'), ('ssl_error', 'SSL Error'), ('invalid_url', 'Invalid URL'), ('connection_error', 'Connection Error'), ('protected', 'Protected')], db_index=True, default='unknown', max_length=50),
        ),
    ]
