# Generated by Django 5.2.13 on 2026-05-13 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_website_status'),
        ('searches', '0005_searchquerytask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel')], default='csv', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='created', max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='searches.search')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='leads_expor_user_id_30a20b_idx'), models.Index(fields=['status'], name='leads_expor_status_ef55ef_idx'), models.Index(fields=['expires_at'], name='leads_expor_expires_b25b11_idx')],
            },
        ),
    ]
