# Generated by Django 5.2.13 on 2026-05-13 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_exporthistory'),
        ('searches', '0005_searchquerytask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEnrichmentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('single', 'Single Lead'), ('bulk', 'Bulk Leads'), ('search', 'Search Leads')], default='single', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('lead_ids', models.JSONField(blank=True, default=list)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('completed_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('skipped_items', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='email_confidence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='email_source_pages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='enrichment_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='enrichment_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='enrichment_last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='enrichment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['enrichment_status'], name='leads_lead_enrichm_222a25_idx'),
        ),
        migrations.AddField(
            model_name='leadenrichmentjob',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrichment_jobs', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadenrichmentjob',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrichment_jobs', to='searches.search'),
        ),
        migrations.AddField(
            model_name='leadenrichmentjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='leadenrichmentjob',
            index=models.Index(fields=['user', 'status'], name='leads_leade_user_id_188141_idx'),
        ),
        migrations.AddIndex(
            model_name='leadenrichmentjob',
            index=models.Index(fields=['job_type', 'status'], name='leads_leade_job_typ_2f7576_idx'),
        ),
        migrations.AddIndex(
            model_name='leadenrichmentjob',
            index=models.Index(fields=['created_at'], name='leads_leade_created_89b22e_idx'),
        ),
    ]
