# Generated by Django 5.2.13 on 2026-05-13 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_leadenrichmentjob_lead_email_confidence_and_more'),
        ('searches', '0005_searchquerytask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exporthistory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exporthistory',
            name='export_scope',
            field=models.CharField(choices=[('all', 'All Filtered Leads'), ('search', 'Search Leads'), ('selected', 'Selected Leads'), ('lead_list', 'Lead List')], db_index=True, default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='exporthistory',
            name='file_size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exporthistory',
            name='lead_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='leads.leadlist'),
        ),
        migrations.AddField(
            model_name='exporthistory',
            name='selected_lead_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exporthistory',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exporthistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='exporthistory',
            index=models.Index(fields=['export_type'], name='leads_expor_export__47c8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='exporthistory',
            index=models.Index(fields=['export_scope'], name='leads_expor_export__b5bcdc_idx'),
        ),
    ]
