# Generated by Django 5.2.13 on 2026-05-12 16:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_status', models.CharField(choices=[('beta', 'Beta'), ('active', 'Active'), ('limited', 'Limited'), ('suspended', 'Suspended'), ('blocked', 'Blocked')], default='beta', max_length=20)),
                ('beta_access', models.BooleanField(default=True)),
                ('searches_today', models.PositiveIntegerField(default=0)),
                ('exports_today', models.PositiveIntegerField(default=0)),
                ('leads_today', models.PositiveIntegerField(default=0)),
                ('searches_this_month', models.PositiveIntegerField(default=0)),
                ('exports_this_month', models.PositiveIntegerField(default=0)),
                ('leads_this_month', models.PositiveIntegerField(default=0)),
                ('max_searches_per_day', models.PositiveIntegerField(default=5)),
                ('max_searches_per_month', models.PositiveIntegerField(default=100)),
                ('max_exports_per_day', models.PositiveIntegerField(default=3)),
                ('max_exports_per_month', models.PositiveIntegerField(default=50)),
                ('max_leads_per_search', models.PositiveIntegerField(default=300)),
                ('max_leads_per_day', models.PositiveIntegerField(default=1000)),
                ('max_leads_per_month', models.PositiveIntegerField(default=5000)),
                ('unlimited_searches', models.BooleanField(default=False)),
                ('unlimited_exports', models.BooleanField(default=False)),
                ('unlimited_leads', models.BooleanField(default=False)),
                ('daily_reset_at', models.DateField(default=django.utils.timezone.localdate)),
                ('monthly_reset_at', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Usage',
                'verbose_name_plural': 'User Usage',
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('search_created', 'Search Created'), ('search_blocked', 'Search Blocked'), ('lead_saved', 'Lead Saved'), ('lead_blocked', 'Lead Blocked'), ('export_created', 'Export Created'), ('export_blocked', 'Export Blocked'), ('limit_reset', 'Limit Reset')], max_length=50)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='usage_usage_user_id_399e4f_idx'), models.Index(fields=['created_at'], name='usage_usage_created_cca628_idx')],
            },
        ),
    ]
