# Generated by Django 5.2.13 on 2026-05-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userusage',
            name='auto_clear_raw_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userusage',
            name='auto_delete_old_exports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userusage',
            name='auto_delete_old_leads',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userusage',
            name='export_retention_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='userusage',
            name='lead_retention_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='userusage',
            name='raw_data_retention_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='userusage',
            name='search_history_retention_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
