# Generated by Django 5.2.13 on 2026-05-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='email_enrichment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='search',
            name='max_leads',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='search',
            name='scrape_mode',
            field=models.CharField(default='safe', max_length=20),
        ),
    ]
