# Generated by Django 5.2.13 on 2026-05-09 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0002_search_email_enrichment_search_max_leads_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='search',
            name='completed_tasks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='search',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='scrape_mode',
            field=models.CharField(choices=[('safe', 'Safe'), ('balanced', 'Balanced'), ('deep', 'Deep')], default='safe', max_length=20),
        ),
        migrations.AlterField(
            model_name='search',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='search',
            name='total_tasks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='search',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['user', 'status'], name='searches_se_user_id_ccc8bc_idx'),
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['user', 'created_at'], name='searches_se_user_id_60cd49_idx'),
        ),
    ]
