# Generated by Django 5.2.13 on 2026-05-12 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0004_search_updated_at_alter_search_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('query_text', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('max_leads', models.PositiveIntegerField(default=100)),
                ('leads_found', models.PositiveIntegerField(default=0)),
                ('processed_index', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=1)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='search',
            name='searches_se_user_id_60cd49_idx',
        ),
        migrations.RemoveField(
            model_name='search',
            name='query_list',
        ),
        migrations.AddField(
            model_name='search',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='failed_tasks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='search',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='search',
            name='locations',
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['created_at'], name='searches_se_created_108304_idx'),
        ),
        migrations.AddField(
            model_name='searchquerytask',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_tasks', to='searches.search'),
        ),
        migrations.AddIndex(
            model_name='searchquerytask',
            index=models.Index(fields=['search', 'status'], name='searches_se_search__e75882_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquerytask',
            index=models.Index(fields=['keyword', 'location'], name='searches_se_keyword_475a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquerytask',
            index=models.Index(fields=['created_at'], name='searches_se_created_a66f57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='searchquerytask',
            unique_together={('search', 'keyword', 'location')},
        ),
    ]
